name: CI

on:
  - push
  - pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install libusb
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-dev libusb-1.0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: thumbv6m-none-eabi

      # We can't currently use actions-rs/cargo because it doesn't
      # support a working-directory argument, and --manifest-path
      # ignores firmware/.cargo/config.
      # See https://github.com/actions-rs/cargo/issues/6
      # We also can't use Clippy until this is resolved:
      # https://github.com/actions-rs/clippy-check/issues/28
      - name: Check software
        working-directory: software
        run: cargo build

      - name: Check firmware
        working-directory: firmware
        run: cargo build --release
